### ISSUE TITLE
Too many domains for accessing the service

### ISSUE THREAD

**Issue by esuomi** [HSLdevcom/digitransit-ui#1364]
There's at least the following URLs to access the new service:
 - https://beta.reittiopas.fi
 - https://opas.matka.fi
 - https://beta.matka.fi

Please be reasonable and have just one. Yes, I did notice the curious difference between HSL and Liikennevirasto ones where latter actually allows me to browse eg. Rovaniemi's local buses instead of just Helsinki but from user's point of view _that should not matter_. It's better to have everything in one service anyway.

**Comment by tuukka** [comment]
reittiopas.fi and beta.reittiopas.fi currently point to the same HSL service because the beta users would lose their client-side (per-domain) profile data before we have implemented server-side profile data. dev.reittiopas.fi is an unstable version for development and testing purposes.

opas.matka.fi and beta.matka.fi point to another service offered by Finnish Transport Agency. It differs from HSL Reittiopas in scope, use cases, data sources, data quality, configuration parameters, branding etc. If you search for "oulu" in Reittiopas, we want to show Oulunkylä and Ouluntie; in Matka.fi, we want to show "Oulu (city)", "Oulu (railway station)", "Oulu airport" etc.

There's a third set of services provided by Waltti cities: https://joensuu.digitransit.fi/ https://turku.digitransit.fi/ https://oulu.digitransit.fi/ https://lappeenranta.digitransit.fi/ https://kuopio.digitransit.fi/ https://hameenlinna.digitransit.fi/

**Comment by esuomi** [comment]
So you're saying my point stands and the situation is even worse than I thought. Alright :)

**Comment by Macroz** [comment]
There are distinct dev and beta instances that are not required for normal users, and not used in communication (anymore). So I don't see any confusion here anymore. Developers obviously may want to use one or the other for obvious reasons. Since 15.2. there is the official production version for normal use.

Reittiopas, Matka and Waltti versions are as planned, because they are for distinct sets of users. The responsible organizations also communicate their versions to their target groups.

Closing this issue. I think the point is well known already.
