### ISSUE TITLE
Enable Service Worker to be able to turn this into a PWA

### ISSUE THREAD

**Issue by deiga** [HSLdevcom/digitransit-ui#1686]
The app works reasonably well on mobile and pushing it to be a standalone (PWA) would be great!

It would enable the usage of Native API's like Push API for notifications

**Comment by hannesj** [comment]
This should be fixed by https://github.com/HSLdevcom/digitransit-ui/pull/1666

A ServiceWorker is installed on http://dev.reittiopas.fi/

**Comment by kalon33** [comment]
Dear @hannesj is that included in all Digitransit setups using latest master, or should we activate/configure something to use it as standalone app?

That's indeed a nice feature to have.
----- Mail d'origine -----
De: Hannes Junnila <notifications@github.com>
À: HSLdevcom/digitransit-ui <digitransit-ui@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Envoyé: Wed, 12 Jul 2017 16:27:08 +0200 (CEST)
Objet: Re: [HSLdevcom/digitransit-ui] Enable Service Worker to be able to turn this into a PWA (#1686)

This should be fixed by https://github.com/HSLdevcom/digitransit-ui/pull/1666

A ServiceWorker is installed on http://dev.reittiopas.fi/

**Comment by hannesj** [comment]
@kalon33 it works as long as the BUILD_TIME variable in buildInfo.js is not 'unset'. We do this cahnge in the docker build shell script.
