### ISSUE TITLE
Total number of citybike slots can be wrong

### ISSUE THREAD

**Issue by ttsirkia** [HSLdevcom/digitransit-ui#2774]
If there are more bikes in the bike station than slots, the total number of slots is shown incorrectly.

```
totalSpaces={station.bikesAvailable + station.spacesAvailable}
```

There can be 10 slots, 40 bikes available => the result will be 40/40 bikes instead of 40/10. (`spacesAvailable` is zero)

https://github.com/HSLdevcom/digitransit-ui/blob/master/app/component/CityBikeContent.js#L21

**Comment by ttsirkia** [comment]
It seems that the API doesn't provide the total number of slots. So this cannot be fixed without changing the API. One possibility would be that the `spacesAvailable` is negative, if there are more bikes than slots but may break some apps.

**Comment by optionsome** [comment]
Thank you for the information. We fetch the information about the stations from http://helsinki-fi.smoove.pro/api-public/stations and then we process it in OpenTripPlanner which provides the API UI uses. The original API seems to provides total_slots which we do not currently use. In theory, we could add a new value to the stations in the OpenTripPlanner GraphlQL API that would tell this total_slots value.

This also made me realise that the routing does not really work as it should on those Helsinki/Espoo citybike stations because the stations allow overflow but OpenTripPlanner cannot route to "full" stations. There are at least couple of solutions for fixing that issue that could also affect the spacesAvailable value coming from routing API:
1. Ignore the spacesAvailable value in routing, return the value as it is now  and add a new value for the stations that tells if overflow is allowed and that value could also be fetched through the GraphlQL routing API
2. Use default Integer.MAX_VALUE (2147483647) value for the spacesAvailable so that the routing would always work to open stations but then the API would return that value as spacesAvailable which could potentially break some systems that use the API and the value is not really informative.

**Comment by optionsome** [comment]
Took a while to fix this but now it's fixed in the newer version of digitransit-ui (found in next branch). We added a new capacity field to what our API (https://github.com/hsldevcom/OpenTripPlanner) returns and utilized it in UI to display the correct capacity.
