### ISSUE TITLE
Unable to open favorites tab without performing another action beforehand

### ISSUE THREAD

**Issue by BodoMinea** [HSLdevcom/digitransit-ui#3204]
As of now, one is unable to open favorites tab without performing another action beforehand. This happens no matter if there are or not any favorite lines/trips already added. In order to be able to open the tab, I need to first select a station or route from the Near You tab or via the search function. No relevant JS error is given in the dev tools console (also checked on my local dev instance - this also happens, and also no error message is thrown).

![Matka fi](https://user-images.githubusercontent.com/7822580/79351222-16c78e00-7f41-11ea-81e4-9e6083af8cdf.gif)

After any subsequent interaction with a stop or route, the favorites tab works normally - adding, clicking etc.

**Comment by optionsome** [comment]
It is confusing but I think it is like that "by design". We have a new design we are currently implementing, which current situation you can follow in next branch. There we have completely removed that side bar and we plan to implement favourites and near you features a bit differently. Unfortunately we don't yet have material about the new design in English.

**Comment by hbruch** [comment]
We decided to change that designed behavior in our fork. These changes, originally from Vlatko Vlahek (@vlaja)  were sufficient and we experienced no negative side effects so far: https://github.com/mfdz/digitransit-ui/pull/53/files

**Comment by BodoMinea** [comment]
@optionsome okay, I'll also take a look on the next branch.

@hbruch that worked perfectly! Thank you very much. I think I can close this issue now.
