### ISSUE TITLE
Configuring digitransit-ui

### ISSUE THREAD

**Issue by dancesWithCycles** [HSLdevcom/digitransit-ui#4180]
Hi folks,
Thank you very much for creating and maintaining this repository. I am new to digitransit-ui and would like to run a costume instance.

I found the configuration files including the default file `config.default.js` at the path `app/configuration`. I could not find documentation or explanation of the config options/switches yet. Does anything like this exist? How do you recommend someone to study digitransit-ui to deploy and operate a costume version without previous knowledge and starting from scratch?

I appreciate any advice that points me in the right direction. Cheers!

**Comment by optionsome** [comment]
At least for the most part there is unfortunately no documentation for the configuration options. Hopefully some of them have names that tell their purpose but otherwise I think the best way is to check where the configuration options are used. There are also some additional configuration options that are not used in the default config but are in some other configs we use. https://digitransit.fi/en/services/ has some instructions but I'm not quite sure how complete or up-to-date they are. Additionally, I think they created some guide for setting up digitransit in Germany but I couldn't find that documentation now.

**Comment by dancesWithCycles** [comment]
Hi @optionsome ,
Thank you very much for the link to the services description. I was not aware of that.

After reading it all over I come to the conclusion that it does not solve this issue but helps to get a clear overview.

If someone starts to document the configuration, where would you put it in the existing documentation?

Do you mean the following cook book? https://transportkollektiv.github.io/digitransit-setup/index.html It is a nice documentation and could also dive deeper into explaining configuration.

Cheers!

**Comment by optionsome** [comment]
I think the place for the UI configuration documentation would be here in github in this repository's markdown documents that can be linked in the README.

Yes that's the cook book I was looking for.

**Comment by dancesWithCycles** [comment]
Hi @optionsome ,
Thank you very much for clarification. When I'll get my hands dirty in configuring Digitransit UI I'll might write down a configuration on the way and share a pull request.

Cheers!

**Comment by dancesWithCycles** [comment]
Hi folks,
The community might be also interested in this tutorial that also uses the Digitransit project for the user interface.

https://github.com/stadtnavi/stadtnavi-tutorial

Cheers!

**Comment by leonardehrenfried** [comment]
There is also https://transportkollektiv.github.io/digitransit-setup/
