### ISSUE TITLE
Single search box usability issues

### ISSUE THREAD

**Issue by esuomi** [HSLdevcom/digitransit-ui#549]
Beef is in the title; tested on both desktop and by random UAT on a bit older Android phone. Practically the usage flow is so messed up that my random test user got completely fed up after couple minutes and abandoned the site proclaiming that she'll never use this (_=matka.hsl.f_i) again.

---

I found the beta some time ago and I have been using it as a replacement to all available relevant iOS Helsinki public transport transit apps ever since. The latest major UI update was IMO UX wise terrible and I really hope you'll roll it back or at least make it so that the floating box only appears _after_ I have given the web app permission to use my location. Caveat here is that this won't really work with Androids however as latest versions allow for revoking access without notifying the (web)app.

**Comment by Macroz** [comment]
Can you clarify the use case? I can use https://beta.reittiopas.fi both on the desktop as well as on an Android just fine without allowing it to locate me. Note, that we have been working on this part of the app in the last sprints so it has changed quite a bit compared to old versions.

**Comment by esuomi** [comment]
Righto.

Lets say I'm at work on my PC and I need to look up a route from home to local movie theatre. Due to Reasons I can't/won't enable location services so on visiting the site I **1) block location services**.

The box at the top of the screen says "Where to? Address or stop" / "Määränpää, linja tai pysäkki" / "Destination", depending on localization. I'll use EN for the remaining steps. Anyway, as it instructs me to type the target, I'll  **2) type in "Tennispalatsi"**. Now instead of giving me the option of selecting where from I'm coming it automatically decided I want a route from *Rautatieasema, Helsinki* to *Tennispalatsi, Helsinki*.

This is the part where my test user got terribly frustrated, on mobile the usability and clarity dies for two reasons:

 1. It's not obvious you can click the address itself to change it
 2. Clicking the arrow to left (as in *Back*, as in *Maybe I missed something, I want to change this!*) takes back to main screen.

User tension is high at this point. The site decides to asks me to rate the likelyhood of recommending the site to friends/colleagues. You've just aggravated the user, what do you think how high scores you're going to yield? :)

Anyway, lets assume I still want to try to find the route, after all I'm desperate for this information. Second chance, here it comes! The top box still says the same thing so I'll **3) click the top box so that I could type in *Tennispalatsi*** and I'm thrown back to the erroneous view again. This is the point where my test user stopped entirely and I have to stop too, because while I *know* how to get around this, I'm not a typical user by any means.

------

I'm sorry to say but the UX changes you've done in past few sprints are either misinformed or not implemented properly. The logic is gone. Plus the some of the parts even look simply worse, eg. the actual route miniview at the bottom of the screen when one actually does get route suggestions. I personally hate saying things like this as I'm sure there's been considerable effort to implement these changes (I'm a programmer myself too!) but sometimes things just have to be rolled back.

**Comment by Macroz** [comment]
We work mobile first, so the site is not optimized for desktop use yet. In fact it's hardly a responsive app at the current state. You can read about the motivation for changing the route summary from our release notes here https://digitransit.fi/fi/uutiset/2016-04-25-release-markku/ I think you will agree that on mobile devices the simplified display is the way to go.

Also the changes we do regarding UX are based on user feedback and user testing. Obviously we shall also continue to do this and take your feedback into account as well. However, it is unfortunately unlike that the UI will please everybody. Also it takes time to get used to, especially since it is a big change compared to the old Reittiopas. So far we have not discovered big usability or learnability issues regarding this issue that you have brought up.

Digitransit is designed to take advantage of location services, and it will allow you to skip one extra step in the most common use cases. If you choose to not take the advantage of this feature, the upcoming release contains flow improvements in your case. This is one of the many areas, where we have identified a lot of improvements, but just have not had time to implement them all.

You are welcome to come and implement better solutions e.g. with us at the upcoming hackathon https://reittiopas-hackathon.confetti.events/ Also since we are both open source and open data, it's really possible for others to implement alternate UIs. The "Reittiopas" version will have to cater to the "common user".  Advanced, and uncommon use may need something else entirely. Also we are not in the app store, and perhaps optimized apps (from 3rd parties, or from us) will be a part of the digitransit ecosystem later.

I recommend you to check this issue again after the next release and please report back. You can already see the progress in https://beta.reittiopas.fi/ regarding the flow.

**Comment by esuomi** [comment]
Somehow I don't think you read my last comment at all as you seem to have grabbed on to the sentence _"Lets say I'm at work on my PC"_ and then immediately started defending your choices based on that, starting with the statement that you're going mobile first. This detail is irrelevant to the use case I described and I even originally said that the issue arose with Android phone user getting really aggravated.

But I'm digressing here. I'll give you a bit of rope here instead of tightening the noose; lets see in a few weeks (I assume you work in 2 week sprints?) what's happened to the usability.

**Comment by Arkkimaagi** [comment]
The problem is real and I was confused about it too when I opened the beta app today. Having only one field is a big change to the conventional operation (of reittiopas and its competitors) and all use cases should be covered well if such a change is done.

Here's my suggestion:
* If the current location is not available, show two input fields like before. The first one should be blank and not filled with the railway station as it is now. The map can be centered on the railway station, but the input should be blank to invite typing.
* When I focus on the input field, I get a blank screen, no map or anything on the background. Here is one place where I'd show the both fields even if the user has location enabled. If the location is enabled, show "Your current location", If location is not available, the field should be blank.

This way users with no location data available would be catered better and users with location data would still have the same initial simple view, but also an option to adjust the "from" field before doing any search.

**Comment by tuukka** [comment]
We know that this is a critical step in the user experience, but there is no simple solution and we've tried multiple alternative designs. (Device positioning currently works in around 50% of sessions and fails in various ways for the rest.) Knowing the origin is integral in the UI concept (e.g. for Nearby and Favourites tabs).

Since the latest blog post, we've added the map popup describing the origin location and inviting to change if it's not what you want:
![reittiopas-front](https://cloud.githubusercontent.com/assets/76985/16123434/8fcbebfe-33f3-11e6-84db-d4d5b44c29a6.png)

![reittiopas-hakaniemi](https://cloud.githubusercontent.com/assets/76985/16123657/8346c5b0-33f4-11e6-9549-cd2057248f21.png)

We haven't had time to test this properly, but I hope it answers some of your concerns. Likewise, the search dialog tabs may need further improvements.

**Comment by esuomi** [comment]
@tuukka Well, the consensus here is quite clear IMHO - roll back to the version with two inputs. What we currently have is a failed experiment and that's fine, but don't get too overly attached to it. If it doesn't work, it won't work no matter how much effort you put into it.

---

Personally I like what @Arkkimaagi suggests.

**Comment by tuukka** [comment]
@esuomi Nowadays, we're hardly the only journey planning service with a single input field. Two inputs was one of the designs that we experimented with and didn't work: 1. Route search from A to B is just one of the use cases in our concept. 1.1. Route search after manual input of A is just one sub-use case. 2. You need to be able to search for other things in addition to A and B too (stations, bus lines etc.). 3. Two inputs adds visual clutter as well as too many horizontal bars to the front page.

Also, please note that design isn't made by consensus. We will take your comments into account like @Macroz described above.

**Comment by esuomi** [comment]
Hi!

So it's been a while. I've basically stopped using the service now as it doesn't suit my needs anymore; I have moved back to Reitit, my iOS app of choice because it has those two boxes always visible. There was a moment while it didn't work which got me worried but I _think_ the app dev updated it and now it's up and running again. So there's that. Please tell me the name of HSL official and his political affiliation who forced you to do these idiotic changes and I'll use my vote more carefully next time around.

**Comment by hukka** [comment]
We just got a bit more comprehensive user testing report from an external company (before we had done testing with HSL and Digitransit staff). A new sprint started just now, but the feedback will probably be pretty prominent in the next sprint starting in two weeks.

Not sure yet what will be affected, but I'm sure there will be several things that will be changing.

**Comment by esuomi** [comment]
Hello again!

To everyone who finds this issue by chance, the old UI with better UX is still available at https://classic.reittiopas.fi/ :)

**Comment by vesameskanen** [comment]
Entry page now includes two search fields.
