### ISSUE TITLE
Timetable screen question

### ISSUE THREAD

**Issue by apkoponen** [HSLdevcom/digitransit-ui#646]
I've started implementing this view: https://projects.invisionapp.com/share/MY2F0CQ2W#/screens/71160819. Is there more information about the screen anywhere? Mainly, what is the logic for choosing "Näyttelijäntie" to be shown and what is the meaning of *?

**Comment by samuliheljo** [comment]
Sweet, sounds good!

That mockup is slightly old, this is latest:
<img width="403" alt="timetable" src="https://cloud.githubusercontent.com/assets/1298522/15625988/0ff37496-24c2-11e6-878c-e3a942bdeba8.png">

(https://projects.invisionapp.com/share/5X5RNXGGU#/screens/130673121)

For now, you can ignore this "header part" and concentrate on actual timetables:

<img width="371" alt="header" src="https://cloud.githubusercontent.com/assets/1298522/15625991/231f9554-24c2-11e6-8b77-1fee2fae21ed.png">

**Logic:**

- Drop down "Hakaniemi -> Malminkartano" should select the direction for the route. Note that it is possible to have more than 2, that's why it's a drop down.
- "Valittu päivä: Tänään" should open Drop down that has (Today, Tomorrow, date1, date2) - check logic from itinerary summary page (https://beta.reittiopas.fi/reitti/Latokartanonkaari%203%2C%20Helsinki%3A%3A60.22803649999999%2C25.015131500000003/Kamppi%2C%201244%3A%3A60.16905140000004%2C24.93223419999999)
- "Pyöräilystadion" and "Ohjaajantie" dropdown should be used to select the stop where timetables are calculated

Does this make sense to you? How can I help?

**Comment by apkoponen** [comment]
Hi,

yes it does make sense. Although I think the first bullet point (Drop down "Hakaniemi -> Malminkartano") belongs to the responsibilities of the header, not belong the schedule component, because it is shared by both the stops and schedules view. However, it doesn't affect the implementation, because the pattern used for GraphQL comes from the top container.

A-P

**Comment by hannesj** [comment]
The data itself should be should be quite easy to fetch after an update to the GraphQL endpoint using a query like [this](http://dev.hsl.fi/graphql/console/?query={%0A%20%20pattern%28id%3A%20%22HSL%3A1001%3A0%3A01%22%29%20{%0A%20%20%20%20stops%20{name}%0A%20%20%20%20trips%20{%0A%20%20%20%20%20%20serviceId%0A%20%20%20%20%20%20stoptimes%20{%0A%20%20%20%20%20%20%20%20scheduledArrival%0A%20%20%20%20%20%20%20%20scheduledDeparture%0A%20%20%20%20%20%20}%0A%20%20%20%20}%0A%20%20}%0A}). Unfortunately it is not currently possible to filter out the trips by date or get more detailed information from the service regarding the validity, so one of those has to be implemented before. The stoptimeesForDate only affects the real-time information and does not filter according to the service which it probably(?) should do.

**Comment by apkoponen** [comment]
Yea, it seems a bit odd. I'd expect stoptimesForDate to actually only the stoptimes for the date. I guess could do the filtering based on trip serviceDay, but can't find documentation for it.

**Comment by samuliheljo** [comment]
Yes, that's true direction selection should be part of the header.

**Situation at the HSL**
We are working in 2 week sprints and our goal for this sprint is to "finalize" UI for the beta launch that will happen on 15th June in Nordic Public Transport 2016 conference in Helsinki (http://nordicpublictransport.com/).

This means that we have limited possibilities to add new APIs during this time.

**Suggestion how to proceed**
I suggest that you start this by creating Timetable user interface that uses mock data. Once UI is ready we can hook it to API. We have estimated that it would take probably one day for us to create APIs needed. Basically, data should be fetched using GraphQL, so a solution that takes this into account is right way to go.

Once UI is ready, we can work together to hook it to backend.

Would this be ok for you?

**Comment by samuliheljo** [comment]
Also, note that we are moving from CoffeeScript to ECMAScript, so this should be done using ES.
https://github.com/HSLdevcom/digitransit-ui/blob/master/docs/Architecture.md

**Comment by apkoponen** [comment]
I'll contribute in any way that is most suitable for you guys. I just picked that view as it seemed like a simple, isolated component that I could get started with.

I'm not sure how much time I can input, but I'll push an initial PR for review as soon as I have the layout built.

Thanks for the note, I started they layout with CoffeeScript, but I'll transform it into ES6.

A-P

**Comment by samuliheljo** [comment]
Sounds good, all help is appreciated!

On Tuesday, 31 May 2016, A-P Koponen <notifications@github.com> wrote:

> I'll contribute in any way that is most suitable for you guys. I just
> picked that view as it seemed like a simple, isolated component that I
> could get started with.
>
> I'm not sure how much time I can input, but I'll push an initial PR for
> review as soon as I have the layout built.
>
> Thanks for the note, I started they layout with CoffeeScript, but I'll
> transform it into ES6.
>
> A-P
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/HSLdevcom/digitransit-ui/issues/646#issuecomment-222709299>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPQWkywc0h46Z-dRkOZVruOMJ9FVHXsks5qHEgzgaJpZM4Io7bK>
> .
>


-- 

--
Samuli Heljo
+358 50 3537299

**Comment by apkoponen** [comment]
Was there a design for the case, when no trips exist for the given date? This is the case in e.g. /linjat/HSL:1062:0:01 for saturday and sunday.

**Comment by apkoponen** [comment]
The PR was merged.
