### ISSUE TITLE
Back button should be visible more often

### ISSUE THREAD

**Issue by ttsirkia** [HSLdevcom/digitransit-ui#763]
When opening favourites or vehicles nearby, the navigation bar in the top should have back button.

Currently, it is quite unintuitive that you have to click the button in the bottom again or click the "reittiopas.fi" link in the top bar to get back. Showing the back button always when the user has moved away from the starting view would make the UI more consistent and easier to use.

**Comment by Macroz** [comment]
Hey!

Thanks for the comments. First of all there is a small bug with regards to z-index in the beta version. This is already fixed in the dev version. In that version there is a separate close button and the main menu is not shown when you have opened a tab.

Secondly, there is an alternative design for the look for the tab that is not yet implemented. It does not make the tab fullscreen. It also does not show the back button, but perhaps it could. Opening the tab is not the same as navigating to a new page, but perhaps it's the same as opening the fullscreen map on other pages.Back  button works in the fullscreen map case by returning to the non-fullscreen mode.

**Comment by tuukka** [comment]
Closing as the tabs now have the close button.
